### ISSUE TITLE
question about mm_shuffle_ps

### ISSUE THREAD

**Issue by ghost** [mayah/x86intrin#4]
Hi,

I've got a small problem with mm_shuffle_ps.
When I run the example shuffle.rs, whatever value i use for the control, I never get any value from the second vector.
mm_shuffle_ps seems to always use only one vector.
Maybe I've misunderstood something, but it seems shufps can shuffle the two vectors.

I used last nightly.

**Comment by mayah** [comment]
Thanks for the report. Looking at the mm_shuffle_ps code, it looks just a bug...
I thought I wrote tests for all functions, however, I didn't write a test for mm_shuffle_ps :cry:

I'll fix it soon.

**Comment by mayah** [comment]
I've published the fixed version (v0.4.2) in crates.io.

Closing the bug. If you find any flaws, feel free to reopen.

**Comment by ghost** [comment]
thanks :-)
