### ISSUE TITLE
_MM_SET_DENORMALS_ZERO_MODE

### ISSUE THREAD

**Issue by Boscop** [mayah/x86intrin#6]
I noticed this crate provides `_MM_SET_FLUSH_ZERO_MODE()` but not `_MM_SET_DENORMALS_ZERO_MODE()`.
Is is possible to provide `_MM_SET_DENORMALS_ZERO_MODE()`, too?

https://software.intel.com/en-us/node/523328

**Comment by mayah** [comment]
Ah, gotcha. maybe I've forgotten adding them...

**Comment by mayah** [comment]
Done. Released v0.4.3.
